// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCarForum.Data;

#nullable disable

namespace SimpleCarForum.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216152829_SeedPosts")]
    partial class SeedPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier of the category");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Description of the category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the category");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("Categories for the posts");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Discussions about engines, tuning, performance upgrades, turbo setups, and power optimization.",
                            Name = "Engine & Performance"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Troubleshooting issues, regular maintenance, DIY repairs, and service advice.",
                            Name = "Maintenance & Repairs"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Battery problems, sensors, ECU errors, OBD diagnostics, and electrical system discussions.",
                            Name = "Electrical & Diagnostics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Car buying tips, resale advice, market insights, and vehicle recommendations.",
                            Name = "Buying & Selling Advice"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Open discussions about cars, brands, news, and automotive trends.",
                            Name = "General Discussion"
                        });
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier of the comment");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Identifier of the comment's author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Text content of the comment");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when comment was created");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the related post");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", t =>
                        {
                            t.HasComment("Comments for posts");
                        });
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier of the post");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Identifier of the post's author");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Identifier of the post's category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Content of the post");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when post was created");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Title of the post");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", t =>
                        {
                            t.HasComment("Post class");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 1,
                            Content = "Looking for reliable turbo upgrade options for daily driving with moderate power gains. Any proven setups?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Best Turbo Setup for 2.0 TDI?"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 1,
                            Content = "Is going Stage 2 really worth the additional stress on the engine components?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Stage 1 vs Stage 2 – Worth the Risk?"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 1,
                            Content = "Experiencing misfires at high RPM after remap. Spark plugs and coils are new. What else to check?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "High RPM Misfire After Tune"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 2,
                            Content = "What oil change interval do you follow for turbocharged petrol engines?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Oil Change Interval – 8k or 10k km?"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 2,
                            Content = "Looking for durable brake pads for mixed city and highway driving.",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Brake Pads Recommendation"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 2,
                            Content = "Losing coolant slowly but no visible leak. Where should I start diagnosing?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Coolant Leak – Hard to Detect"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 3,
                            Content = "Got P0420 code. Is it always catalytic converter failure?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Check Engine Light – P0420"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 3,
                            Content = "Brand new battery but drains overnight. Possible parasitic draw?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Battery Drains Overnight"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 3,
                            Content = "Looking for a reliable OBD2 scanner for home diagnostics.",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "OBD Scanner Recommendations"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 4,
                            Content = "Which is the smarter buy considering maintenance and fuel prices?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Used Diesel vs Petrol in 2025?"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 4,
                            Content = "Is buying a 250k km car always a bad decision?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "High Mileage Car – Red Flag?"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 4,
                            Content = "Looking for reliable SUV under reasonable budget with low maintenance costs.",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Best Budget SUV?"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 5,
                            Content = "In your experience, which brand has proven most reliable over the years?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Most Reliable Car Brand?"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 5,
                            Content = "Do you still prefer manual transmission in modern cars?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Manual vs Automatic – Still Relevant?"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            AuthorId = "11111111-1111-1111-1111-111111111111",
                            CategoryId = 5,
                            Content = "Do you think EVs will fully replace internal combustion engines?",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Future of Electric Vehicles"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SimpleCarForum.Infra.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SimpleCarForum.Infra.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleCarForum.Infra.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SimpleCarForum.Infra.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Comment", b =>
                {
                    b.HasOne("SimpleCarForum.Infra.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleCarForum.Infra.Data.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Post", b =>
                {
                    b.HasOne("SimpleCarForum.Infra.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleCarForum.Infra.Data.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SimpleCarForum.Infra.Data.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
